# Generated by Django 4.0.6 on 2023-01-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardentyouth_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Objective1', models.TextField()),
                ('Objective2', models.TextField()),
                ('Objective3', models.TextField()),
                ('Objective4', models.TextField()),
                ('Objective5', models.TextField()),
            ],
        ),
    ]
